apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: efs-static 
spec:
  capacity:
    storage: 5Gi # Dummy, size in elastic
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "" # should be empty in static
  persistentVolumeReclaimPolicy: Retain 
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-05e8597ec2a200f2d
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "" 
  resources:
    requests:
      storage: 5Gi 
---
apiVersion: v1
kind: Pod
metadata: 
  name: efs-static
  labels:
    purpose: efs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-html
    persistentVolumeClaim:
      claimName: efs-static

