# headless service
apiVersion: v1
kind: Service 
metadata:
  name: nginx-headless
  labels:
    app: nginx
    purpose: stateful-demo 
spec:
  clusterIP: None
  selector:
    app: nginx
    purpose: stateful-demo
  ports:
    - protocol: TCP 
      port: 80 # service port 
      name: web
---
# normal service
apiVersion: v1 
kind: Service 
metadata:
  name: nginx
  labels: 
    app: nginx
    purpose: stateful-demo
spec:
  selector:
    app: nginx
    purpose: stateful-demo
  ports:
    - protocol: TCP 
      port: 80 # service port
      name: web
---
apiVersion: apps/v1 
kind: StatefulSet 
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      purpose: stateful-demo
  serviceName: "nginx-headless" # this should be headless service name
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
        purpose: stateful-demo
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80 
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
    # this is PVC
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs" 
      resources:
        requests:
          storage: 1Gi 
